import { useState, useEffect } from "react";

export function ThreatLogsPage() {
	const [logs, setLogs] = useState<any[]>([]);

	useEffect(() => {
		const fetchLogs = async () => {
			try {
				const response = await fetch("http://localhost:8000/api/threat-logs");
				const data = await response.json();
				setLogs(data.logs || []);
			} catch (error) {
				console.error("Failed to fetch threat logs:", error);
			}
		};

		fetchLogs();
		const interval = setInterval(fetchLogs, 2000);
		return () => clearInterval(interval);
	}, []);

	return (
		<div className="flex flex-col gap-6 h-full">
			<header className="flex items-center justify-between gap-3 shrink-0">
				<div>
					<h1 className="text-2xl font-semibold text-text">Threat Logs</h1>
					<p className="text-sm text-text-muted">Historical record of alerts generated by SENTRi-X.</p>
				</div>
				<div className="flex items-center gap-2">
					<input
						placeholder="Search flows, IPs, threat class..."
						className="bg-surface border border-border rounded-xl px-3 py-1.5 text-xs text-text placeholder:text-text-muted min-w-64"
					/>
					<button className="px-3 py-1.5 rounded-xl bg-surface-subtle border border-border text-xs text-text">
						Filter Rules
					</button>
					<button className="px-3 py-1.5 rounded-xl bg-accent hover:bg-accent-dark text-xs text-accent-dark border border-accent">
						Export CSV
					</button>
				</div>
			</header>
				<div className="rounded-2xl bg-surface/80 backdrop-blur-md border border-border/80 p-4 text-xs overflow-auto shadow-md flex-1">
					<table className="w-full border-separate border-spacing-y-1">
						<thead className="text-text-muted sticky top-0 bg-surface z-10">
						<tr>
							<th className="text-left px-3 py-2">Timestamp</th>
							<th className="text-left px-3 py-2">Source IP</th>
							<th className="text-left px-3 py-2">Destination IP</th>
							<th className="text-left px-3 py-2">Threat Class</th>
							<th className="text-left px-3 py-2">AI Confidence</th>
							<th className="text-left px-3 py-2">Status</th>
						</tr>
					</thead>
						<tbody>
							{logs.length === 0 ? (
								<tr><td colSpan={6} className="text-center py-4 text-text-muted">Waiting for threat data...</td></tr>
							) : logs.map((log) => (
								<tr key={log.id} className="bg-surface-subtle hover:bg-background-soft">
									<td className="px-3 py-2 text-text">{log.timestamp}</td>
									<td className="px-3 py-2">{log.source_ip}</td>
									<td className="px-3 py-2">{log.dest_ip}</td>
									<td className="px-3 py-2">
										<span className="px-2 py-0.5 rounded-full bg-accent-soft text-accent-dark border border-accent inline-block">
											{log.attack_type}
										</span>
									</td>
									<td className="px-3 py-2 text-accent-dark font-semibold">{(log.confidence * 100).toFixed(1)}%</td>
									<td className="px-3 py-2">
										<span className="px-2 py-0.5 rounded-full bg-rose-500/10 text-rose-500 border border-rose-500/20">
											{log.status || 'Alerted'}
										</span>
									</td>
								</tr>
							))}
						</tbody>
					</table>
				</div>
		</div>
	)
}
