import { useState, useEffect, useMemo } from "react";
import { XaiPreviewModal } from "../../components/XaiPreviewModal";
import { classifyThreatLevel, type ThreatLevel } from "../../utils/threatLevel";

interface ThreatLog {
	id: string;
	timestamp: string;
	source_ip: string;
	dest_ip: string;
	attack_type: string;
	confidence: number;
	threat_level?: ThreatLevel;
	status: string;
	shap_values?: Array<{ f: string; v: number }>;
	lime_values?: Array<{ f: string; v: number }>;
}

interface FilterRules {
	minConfidence: number;
	attackTypes: string[];
}

export function ThreatLogsPage() {
	const [logs, setLogs] = useState<ThreatLog[]>([]);
	const [searchQuery, setSearchQuery] = useState("");
	const [filterRules, setFilterRules] = useState<FilterRules>({
		minConfidence: 0,
		attackTypes: [],
	});
	const [selectedThreat, setSelectedThreat] = useState<ThreatLog | null>(null);
	const [hoveredThreat, setHoveredThreat] = useState<ThreatLog | null>(null);
	const [mousePos, setMousePos] = useState({ x: 0, y: 0 });
	const [showFilterPanel, setShowFilterPanel] = useState(false);

	useEffect(() => {
		const fetchLogs = async () => {
			try {
				const response = await fetch("http://localhost:8000/api/threat-logs");
				const data = await response.json();
				setLogs(data.logs || []);
			} catch (error) {
				console.error("Failed to fetch threat logs:", error);
			}
		};

		fetchLogs();
		const interval = setInterval(fetchLogs, 2000);
		return () => clearInterval(interval);
	}, []);

	// Get unique attack types for filter
	const uniqueAttackTypes = useMemo(() => {
		return [...new Set(logs.map(log => log.attack_type))];
	}, [logs]);

	// Filter and search logs
	const filteredLogs = useMemo(() => {
		return logs.filter(log => {
			// Search filter
			const searchLower = searchQuery.toLowerCase();
			const matchesSearch = 
				log.source_ip.toLowerCase().includes(searchLower) ||
				log.dest_ip.toLowerCase().includes(searchLower) ||
				log.attack_type.toLowerCase().includes(searchLower) ||
				log.timestamp.toLowerCase().includes(searchLower) ||
				log.status.toLowerCase().includes(searchLower);

			if (!matchesSearch) return false;

			// Confidence filter
			if (log.confidence < filterRules.minConfidence / 100) return false;

			// Attack type filter
			if (filterRules.attackTypes.length > 0) {
				if (!filterRules.attackTypes.includes(log.attack_type)) return false;
			}

			return true;
		});
	}, [logs, searchQuery, filterRules]);

	// Export to CSV
	const handleExportCSV = () => {
		if (filteredLogs.length === 0) {
			alert("No logs to export");
			return;
		}

		const headers = ["Timestamp", "Source IP", "Destination IP", "Threat Class", "AI Confidence", "Status"];
		const csvContent = [
			headers.join(","),
			...filteredLogs.map(log =>
				[
					`"${log.timestamp}"`,
					`"${log.source_ip}"`,
					`"${log.dest_ip}"`,
					`"${log.attack_type}"`,
					`"${(log.confidence * 100).toFixed(1)}%"`,
					`"${log.status}"`,
				].join(",")
			),
		].join("\n");

		const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
		const link = document.createElement("a");
		const url = URL.createObjectURL(blob);
		link.setAttribute("href", url);
		link.setAttribute("download", `threat-logs-${new Date().toISOString().split('T')[0]}.csv`);
		link.style.visibility = "hidden";
		document.body.appendChild(link);
		link.click();
		document.body.removeChild(link);
	};

	const handleToggleAttackType = (type: string) => {
		setFilterRules(prev => {
			const newTypes = prev.attackTypes.includes(type)
				? prev.attackTypes.filter(t => t !== type)
				: [...prev.attackTypes, type];
			return { ...prev, attackTypes: newTypes };
		});
	};

	const handleResetFilters = () => {
		setFilterRules({
			minConfidence: 0,
			attackTypes: [],
		});
		setSearchQuery("");
	};

	return (
		<div className="flex flex-col gap-6 h-full">
			<header className="flex items-center justify-between gap-3 shrink-0 flex-wrap">
				<div>
					<h1 className="text-2xl font-semibold text-text">Threat Logs</h1>
					<p className="text-sm text-text-muted">Historical record of alerts generated by SENTRi-X. Click any row to view XAI analysis.</p>
				</div>
				<div className="flex items-center gap-2 flex-wrap">
					<input
						placeholder="Search flows, IPs, threat class..."
						value={searchQuery}
						onChange={(e) => setSearchQuery(e.target.value)}
						className="bg-surface border border-border rounded-xl px-3 py-1.5 text-xs text-text placeholder:text-text-muted min-w-64"
					/>
					<button 
						onClick={() => setShowFilterPanel(!showFilterPanel)}
						className={`px-3 py-1.5 rounded-xl border text-xs font-medium transition-colors ${
							showFilterPanel 
								? 'bg-accent text-white border-accent' 
								: 'bg-surface-subtle border-border text-text hover:bg-background-soft'
						}`}
					>
						Filter Rules
					</button>
					<button 
						onClick={handleExportCSV}
						className="px-3 py-1.5 rounded-xl bg-accent hover:bg-accent-dark text-xs text-white border border-accent transition-colors font-medium"
					>
						Export CSV
					</button>
				</div>
			</header>

			{/* Filter Panel */}
			{showFilterPanel && (
				<div className="rounded-2xl bg-surface/80 backdrop-blur-md border border-border/80 p-4 shadow-md">
					<div className="flex items-center justify-between mb-4">
						<h3 className="text-sm font-bold text-text">Filter Rules</h3>
						<button
							onClick={handleResetFilters}
							className="text-xs px-2 py-1 rounded-lg bg-background-soft border border-border text-text-muted hover:text-text transition-colors"
						>
							Reset All
						</button>
					</div>

					<div className="space-y-4">
						{/* Confidence Filter */}
						<div>
							<label className="text-xs font-semibold text-text-muted uppercase mb-2 block">
								Minimum Confidence: {filterRules.minConfidence}%
							</label>
							<input
								type="range"
								min="0"
								max="100"
								value={filterRules.minConfidence}
								onChange={(e) =>
									setFilterRules(prev => ({
										...prev,
										minConfidence: parseInt(e.target.value),
									}))
								}
								className="w-full h-2 bg-background-soft rounded-lg appearance-none cursor-pointer accent-accent"
							/>
						</div>

						{/* Attack Type Filter */}
						<div>
							<label className="text-xs font-semibold text-text-muted uppercase mb-2 block">
								Threat Classes ({filterRules.attackTypes.length} selected)
							</label>
							<div className="flex flex-wrap gap-2">
								{uniqueAttackTypes.map(type => (
									<button
										key={type}
										onClick={() => handleToggleAttackType(type)}
										className={`px-3 py-1 rounded-lg text-xs font-medium transition-colors border ${
											filterRules.attackTypes.includes(type)
												? 'bg-accent text-white border-accent'
												: 'bg-background-soft border-border text-text hover:bg-surface-subtle'
										}`}
									>
										{type}
									</button>
								))}
							</div>
						</div>
					</div>
				</div>
			)}

			{/* Results Summary */}
			<div className="text-xs text-text-muted">
				Showing <span className="font-semibold text-text">{filteredLogs.length}</span> of <span className="font-semibold text-text">{logs.length}</span> threat logs
				{searchQuery && ` (search: "${searchQuery}")`}
				{filterRules.attackTypes.length > 0 && ` (types: ${filterRules.attackTypes.join(", ")})`}
				{filterRules.minConfidence > 0 && ` (confidence ≥ ${filterRules.minConfidence}%)`}
			</div>

			{/* Logs Table */}
			<div className="rounded-2xl bg-surface/80 backdrop-blur-md border border-border/80 p-4 text-xs overflow-auto shadow-md flex-1">
				<table className="w-full border-separate border-spacing-y-1">
					<thead className="text-text-muted sticky top-0 bg-surface z-10">
						<tr>
							<th className="text-left px-3 py-2 font-semibold">Timestamp</th>
							<th className="text-left px-3 py-2 font-semibold">Source IP</th>
							<th className="text-left px-3 py-2 font-semibold">Destination IP</th>
							<th className="text-left px-3 py-2 font-semibold">Threat Class</th>
							<th className="text-left px-3 py-2 font-semibold">AI Confidence</th>
							<th className="text-left px-3 py-2 font-semibold">Status</th>
						</tr>
					</thead>
					<tbody>
						{filteredLogs.length === 0 ? (
							<tr>
								<td colSpan={6} className="text-center py-8 text-text-muted">
									{logs.length === 0 
										? "Waiting for threat data..." 
										: "No threats match your filters. Try adjusting the search or filter rules."}
								</td>
							</tr>
						) : (
							filteredLogs.map((log) => (
								<tr 
									key={log.id} 
									className="bg-surface-subtle hover:bg-background-soft cursor-pointer transition-colors group relative"
									onClick={() => setSelectedThreat(log)}
									onMouseEnter={(e) => {
										setHoveredThreat(log)
										setMousePos({ x: e.clientX, y: e.clientY })
									}}
									onMouseMove={(e) => setMousePos({ x: e.clientX, y: e.clientY })}
									onMouseLeave={() => setHoveredThreat(null)}
								>
									<td className="px-3 py-2 text-text border-y border-l border-border/40 group-hover:border-border rounded-l-lg">
										{log.timestamp.split(' ')[1] || log.timestamp}
									</td>
									<td className="px-3 py-2 font-mono border-y border-border/40 group-hover:border-border">{log.source_ip}</td>
									<td className="px-3 py-2 font-mono border-y border-border/40 group-hover:border-border">{log.dest_ip}</td>
									<td className="px-3 py-2 border-y border-border/40 group-hover:border-border">
										<span className="px-2 py-0.5 rounded-full bg-accent-soft text-accent-dark border border-accent inline-block font-medium">
											{log.attack_type}
										</span>
									</td>
									<td className="px-3 py-2 text-accent-dark font-semibold border-y border-border/40 group-hover:border-border">
										{(log.confidence * 100).toFixed(1)}%
									</td>
									<td className="px-3 py-2 border-y border-r border-border/40 group-hover:border-border rounded-r-lg">
										<span className={`px-2 py-0.5 rounded-full inline-block text-[10px] font-bold ${
											(log.threat_level || classifyThreatLevel(log.confidence)) === 'Critical'
												? 'bg-rose-500/10 text-rose-500 border border-rose-500/20'
												: (log.threat_level || classifyThreatLevel(log.confidence)) === 'High'
													? 'bg-orange-500/10 text-orange-500 border border-orange-500/20'
													: (log.threat_level || classifyThreatLevel(log.confidence)) === 'Medium'
														? 'bg-amber-500/10 text-amber-500 border border-amber-500/20'
														: 'bg-emerald-500/10 text-emerald-500 border border-emerald-500/20'
										}`}>
											{log.threat_level || classifyThreatLevel(log.confidence)}
										</span>
									</td>
								</tr>
							))
						)}
					</tbody>
				</table>
			</div>

			{/* XAI Preview Modal */}
			{selectedThreat && (
				<XaiPreviewModal
					threatId={selectedThreat.id}
					threatType={selectedThreat.attack_type}
					confidence={selectedThreat.confidence}
					threatLevel={selectedThreat.threat_level || classifyThreatLevel(selectedThreat.confidence)}
					sourceIp={selectedThreat.source_ip}
					destIp={selectedThreat.dest_ip}
					timestamp={selectedThreat.timestamp}
					shafeatures={selectedThreat.shap_values || [
						{ f: "src_bytes", v: 0.35 },
						{ f: "dst_pkts", v: 0.25 },
						{ f: "duration", v: 0.15 },
						{ f: "proto_tcp", v: 0.10 },
						{ f: "dst_bytes", v: 0.08 },
					]}
					limefeatures={selectedThreat.lime_values || []}
					isOpen={true}
					onClose={() => setSelectedThreat(null)}
				/>
			)}

			{/* Hover Tooltip */}
			{hoveredThreat && (
				<div 
					className="fixed z-[100] pointer-events-none bg-surface/95 backdrop-blur-xl border border-border/80 shadow-2xl p-4 rounded-xl w-72 transition-opacity"
					style={{ 
						left: Math.min(mousePos.x + 16, window.innerWidth - 300), 
						top: Math.min(mousePos.y + 16, window.innerHeight - 150) 
					}}
				>
					<div className="flex items-center justify-between mb-2">
						<span className="font-bold text-text">{hoveredThreat.attack_type}</span>
						<span className={`px-2 py-0.5 rounded-md text-[10px] font-bold ${(hoveredThreat.threat_level || classifyThreatLevel(hoveredThreat.confidence)) === 'Critical' ? 'bg-rose-500/20 text-rose-500' : (hoveredThreat.threat_level || classifyThreatLevel(hoveredThreat.confidence)) === 'High' ? 'bg-orange-500/20 text-orange-500' : (hoveredThreat.threat_level || classifyThreatLevel(hoveredThreat.confidence)) === 'Medium' ? 'bg-amber-500/20 text-amber-500' : 'bg-emerald-500/20 text-emerald-500'}`}>
							{hoveredThreat.threat_level || classifyThreatLevel(hoveredThreat.confidence)}
						</span>
					</div>
					<p className="text-xs text-text-muted mb-2">
						Flow from <span className="font-mono text-text">{hoveredThreat.source_ip}</span>
					</p>
					<div className="text-[11px] bg-background-soft p-2 rounded-lg border border-border/40 text-text/90 italic">
						"Click to view full XAI analysis and SHAP feature breakdowns."
					</div>
				</div>
			)}
		</div>
	)
}
