export function ThreatLogsPage() {
	const rows = [
		{
			id: 1,
			ts: '10:14:32',
			src: '192.168.1.105',
			dst: '10.0.0.5',
			proto: 'TCP',
			cls: 'DoS Hulk',
			conf: '98.1%',
			status: 'Mitigated',
		},
		{
			id: 2,
			ts: '10:13:08',
			src: '192.168.1.88',
			dst: '10.0.0.5',
			proto: 'TCP',
			cls: 'PortScan',
			conf: '96.4%',
			status: 'Mitigated',
		},
	]

	return (
		<div className="flex flex-col gap-6">
			<header className="flex items-center justify-between gap-3">
				<div>
					<h1 className="text-2xl font-semibold text-text">Threat Logs</h1>
					<p className="text-sm text-text-muted">Historical record of alerts generated by SENTRi-X.</p>
				</div>
				<div className="flex items-center gap-2">
					<input
						placeholder="Search flows, IPs, threat class..."
						className="bg-surface border border-border rounded-xl px-3 py-1.5 text-xs text-text placeholder:text-text-muted min-w-64"
					/>
					<button className="px-3 py-1.5 rounded-xl bg-surface-subtle border border-border text-xs text-text">
						Filter Rules
					</button>
					<button className="px-3 py-1.5 rounded-xl bg-accent hover:bg-accent-dark text-xs text-accent-dark border border-accent">
						Export CSV
					</button>
				</div>
			</header>
				<div className="rounded-2xl bg-surface/80 backdrop-blur-md border border-border/80 p-4 text-xs overflow-x-auto shadow-md">
					<table className="min-w-full border-separate border-spacing-y-1">
						<thead className="text-text-muted">
						<tr>
							<th className="text-left px-3 py-1">Timestamp</th>
							<th className="text-left px-3 py-1">Source IP</th>
							<th className="text-left px-3 py-1">Destination IP</th>
							<th className="text-left px-3 py-1">Protocol</th>
							<th className="text-left px-3 py-1">Threat Class</th>
							<th className="text-left px-3 py-1">AI Confidence</th>
							<th className="text-left px-3 py-1">Status</th>
						</tr>
					</thead>
						<tbody>
							{rows.map((row) => (
								<tr key={row.id} className="bg-surface-subtle hover:bg-background-soft">
									<td className="px-3 py-2 text-text">{row.ts}</td>
									<td className="px-3 py-2">{row.src}</td>
									<td className="px-3 py-2">{row.dst}</td>
									<td className="px-3 py-2">
										<span className="px-2 py-0.5 rounded-full bg-background-soft text-text border border-border">
											{row.proto}
										</span>
									</td>
									<td className="px-3 py-2">
										<span className="px-2 py-0.5 rounded-full bg-accent-soft text-accent-dark border border-accent">
											{row.cls}
										</span>
									</td>
									<td className="px-3 py-2 text-accent-dark font-semibold">{row.conf}</td>
									<td className="px-3 py-2">
										<span className="px-2 py-0.5 rounded-full bg-emerald-50 text-emerald-700 border border-emerald-200">
											{row.status}
										</span>
									</td>
								</tr>
							))}
						</tbody>
					</table>
				</div>
		</div>
	)
}
